# Generated by Django 2.2 on 2021-08-06 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fish_lure_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='all_fish',
            field=models.CharField(choices=[('CR', 'crappie'), ('BS', 'bass'), ('TR', 'trout'), ('WL', 'walleye'), ('ST', 'striper'), ('MU', 'muskie'), ('PI', 'pike'), ('SA', 'salmon')], default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
