# Generated by Django 2.2 on 2021-08-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_fish_all_fish'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='fish_breed',
        ),
    ]
