# Generated by Django 2.2 on 2021-08-12 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_fish_fish_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lure',
            old_name='all_fish',
            new_name='this_fish',
        ),
        migrations.AlterField(
            model_name='fish',
            name='all_fish',
            field=models.CharField(choices=[('CR', 'crappie'), ('BS', 'bass'), ('TR', 'trout'), ('WL', 'walleye'), ('ST', 'striper'), ('MU', 'muskie'), ('PI', 'pike'), ('SA', 'salmon')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
