# Generated by Django 2.2 on 2021-08-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210812_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lure',
            name='this_fish',
            field=models.ManyToManyField(related_name='this_lure', to='main.Fish'),
        ),
    ]
