# Generated by Django 2.2 on 2021-08-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210812_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='all_fish',
            field=models.CharField(choices=[('CR', 'crappie'), ('BS', 'bass'), ('TR', 'trout'), ('WL', 'walleye'), ('ST', 'striper'), ('MU', 'muskie'), ('PI', 'pike'), ('SA', 'salmon')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='fish',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
