# Generated by Django 2.2 on 2021-08-12 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210812_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='fish_reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_reviews', to='main.Fish'),
        ),
    ]
