# Generated by Django 2.2 on 2021-08-13 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210813_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='fish_reviewed',
        ),
        migrations.AddField(
            model_name='review',
            name='fish_reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish_reviews', to='main.Fish'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='lure_reviewed',
        ),
        migrations.AddField(
            model_name='review',
            name='lure_reviewed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lure_reviews', to='main.Lure'),
        ),
    ]
