# Generated by Django 2.2 on 2021-08-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210813_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='all_fish',
            field=models.CharField(choices=[('1', 'Crappie'), ('2', 'Bass'), ('3', 'Trout'), ('4', 'Walleye'), ('5', 'Striper'), ('6', 'Muskie'), ('7', 'Pike'), ('8', 'Salmon')], default='-1', max_length=2),
        ),
    ]
