# Generated by Django 2.2 on 2021-08-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210813_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='all_fish',
            field=models.CharField(choices=[('1', 'Crappie'), ('2', 'Bass'), ('3', 'Trout'), ('4', 'Walleye'), ('5', 'Striper'), ('6', 'Muskie'), ('7', 'Pike'), ('8', 'Salmon'), ('9', 'Please Select a fish!')], default='9', max_length=2),
        ),
    ]
