# Generated by Django 2.2 on 2021-08-14 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20210813_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='all_fish',
        ),
    ]
