# Generated by Django 2.2 on 2021-08-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210816_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='this_fish',
        ),
        migrations.AddField(
            model_name='fish',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
