# Generated by Django 2.2 on 2021-08-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210816_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='lure',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
