# Generated by Django 2.2 on 2021-08-16 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_lure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lure',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
